services:

  customer-db:
    image: postgres:16
    container_name: nexora-customer-db

    environment:
      POSTGRES_DB: customer_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - customer-postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d customer_db"]
      interval: 5s
      timeout: 5s
      retries: 10


  customer-service:
    container_name: nexora-customer-service

    build:
      context: ./services/customer
      dockerfile: Dockerfile

    ports:
      - "5001:8080"

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__CustomerDatabase: "Host=customer-db;Port=5432;Database=customer_db;Username=postgres;Password=postgres"

    depends_on:
      customer-db:
        condition: service_healthy


  catalog-db:
    image: mongo:8
    container_name: nexora-catalog-db

    ports:
      - "27017:27017"

    volumes:
      - catalog-mongo-data:/data/db

    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10


  catalog-service:
    container_name: nexora-catalog-service

    build:
      context: ./services/catalog
      dockerfile: Dockerfile

    ports:
      - "3001:3001"

    environment:
      PORT: 3001
      MONGODB_URI: mongodb://catalog-db:27017/catalog_db

    depends_on:
      catalog-db:
        condition: service_healthy


volumes:
  customer-postgres-data:
  catalog-mongo-data: