services:

  customer-db:
    image: postgres:16
    container_name: nexora-customer-db

    environment:
      POSTGRES_DB: customer_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - customer-postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d customer_db"]
      interval: 5s
      timeout: 5s
      retries: 10


  customer-service:
    container_name: nexora-customer-service

    build:
      context: ./services/customer
      dockerfile: Dockerfile

    ports:
      - "5001:8080"

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__CustomerDatabase: "Host=customer-db;Port=5432;Database=customer_db;Username=postgres;Password=postgres"

    depends_on:
      customer-db:
        condition: service_healthy


  customer-hasura:
    image: hasura/graphql-engine:v2.48.5.cli-migrations-v3
    container_name: nexora-customer-hasura

    ports:
      - "8081:8080"

    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@customer-db:5432/customer_db
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: nexora_customer_admin

    volumes:
      - ./services/customer/hasura/metadata:/hasura-metadata

    depends_on:
      customer-db:
        condition: service_healthy


  catalog-db:
    image: mongo:8
    container_name: nexora-catalog-db

    ports:
      - "27017:27017"

    volumes:
      - catalog-mongo-data:/data/db

    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10


  catalog-service:
    container_name: nexora-catalog-service

    build:
      context: ./services/catalog
      dockerfile: Dockerfile

    ports:
      - "3001:3001"

    environment:
      PORT: 3001
      MONGODB_URI: mongodb://catalog-db:27017/catalog_db

    depends_on:
      catalog-db:
        condition: service_healthy


  inventory-db:
    image: postgres:16
    container_name: nexora-inventory-db

    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5434:5432"

    volumes:
      - inventory-postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d inventory_db"]
      interval: 5s
      timeout: 5s
      retries: 10


  inventory-service:
    container_name: nexora-inventory-service

    build:
      context: ./services/inventory
      dockerfile: Dockerfile

    ports:
      - "5002:8080"

    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://inventory-db:5432/inventory_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

    depends_on:
      inventory-db:
        condition: service_healthy


volumes:
  customer-postgres-data:
  catalog-mongo-data:
  inventory-postgres-data:
